FROM node:22-alpine

ENV FORCE_COLOR=1 \
    NPM_CACHE="/owasp-route/.npm" \
    PNPM_HOME="/pnpm"

ENV NPM_CONFIG_RETRY=5 \
    NPM_CONFIG_TIMEOUT=30000 \
    PATH="$PNPM_HOME:$PATH"

RUN mkdir -p /owasp-route && \
    chown -R node:node /owasp-route

RUN --mount=type=cache,target=${NPM_CACHE} \
    npm install --ignore-scripts -g pnpm --cache ${NPM_CACHE}

WORKDIR /owasp-route

COPY --chmod=444 --chown=root:root package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile --ignore-scripts

COPY __tests__ __tests__
COPY jest.config.ts jest.setup.ts tsconfig.json ./
COPY app app
COPY components components
COPY api api
COPY types types
COPY utils utils

USER node
